[package]
name = "redis-oxide"
version = "0.1.0"
authors = ["David Briggs <email@dpbriggs.ca>"]
edition = "2018"

[dependencies]
tokio = "0.1.17"
shlex = "0.1.1"
promptly = "0.1.5"
nom = "4.2.2"
rand = "0.6.5"
tokio-codec = "0.1.1"
bytes = "0.4.12"
combine = "3.8.1"
partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }
futures = "0.1.25"

[dev-dependencies]
pretty_assertions = "0.6.1"
