[package]
name = "redis-clone"
version = "0.1.0"
authors = ["David Briggs <dpbriggs@edu.uwaterloo.ca>"]
edition = "2018"

[dependencies]
tokio = "0.1.15"
shlex = "0.1.1"
promptly = "0.1.5"
nom = "4.2.1"
rand = "0.6.5"

[dev-dependencies]
pretty_assertions = "0.6.1"
