name: Redis Oxide

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Install Cargo Audit
      run: cargo install --force cargo-audit
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo audit
      run: cargo audit
