name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Cargo Audit
      run: cargo install --force cargo-audit
    - name: Generate Lock File
      run: cargo generate-lockfile
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo audit
      run: cargo audit
